[package]
name = "tiles"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.12"
ratatui = "0.30"
crossterm = "0.29"
union-find = "0.4"
